-- CREATE DATABASE company_db;
-- use company_db;
-- CREATE TABLE EMPLOYEE (EMPNO INT PRIMARY KEY,ENAME VARCHAR(50),JOB VARCHAR(50),MGR INT,HIREDATE DATE,SAL INT,COMM INT,DEPTNO INT);
-- INSERT INTO EMPLOYEE VALUES
-- (7369,'SMITH','CLERK',7902,'1980-12-17',800,NULL,20),
-- (7499,'ALLEN','SALESMAN',7698,'1981-02-20',1600,300,30),
-- (7521,'WARD','SALESMAN',7698,'1981-02-22',1250,500,30),
-- (7566,'JONES','MANAGER',7839,'1981-04-02',2975,NULL,20),
-- (7654,'MARTIN','SALESMAN',7698,'1981-09-28',1250,1400,30),
-- (7698,'BLAKE','MANAGER',7839,'1981-05-01',2850,NULL,30),
-- (7782,'CLARK','MANAGER',7839,'1981-06-09',2450,NULL,10),
-- (7788,'SCOTT','ANALYST',7566,'1987-04-19',3000,NULL,20),
-- (7839,'KING','PRESIDENT',NULL,'1981-11-17',5000,NULL,10),
-- (7844,'TURNER','SALESMAN',7698,'1981-09-08',1500,0,30),
-- (7876,'ADAMS','CLERK',7788,'1987-05-23',1100,NULL,20),
-- (7900,'JAMES','CLERK',7698,'1981-12-03',950,NULL,30),
-- (7902,'FORD','ANALYST',7566,'1981-12-03',3000,NULL,20),
-- (7934,'MILLER','CLERK',7782,'1982-01-23',1300,NULL,10);
-- CREATE TABLE DEPARTMENT (DEPTNO INT PRIMARY KEY,DNAME VARCHAR(50),LOC VARCHAR(50));
-- INSERT INTO DEPARTMENT VALUES
-- (10, 'ACCOUNTING', 'NEW YORK'),
-- (20, 'RESEARCH', 'DALLAS'),
-- (30, 'SALES', 'CHICAGO'),
-- (40, 'OPERATIONS', 'BOSTON');
-- CREATE TABLE GRADE (GRADE INT,LOSAL INT,HISAL INT);
-- INSERT INTO GRADE VALUES
-- (1,700,1200),
-- (2,1201,1400),
-- (3,1401,2000),
-- (4,2001,3000),
-- (5,3001,9999);
-- select * from EMPLOYEE;
-- select EMPNO,ENAME,SAL from EMPLOYEE;
-- select distinct JOB from EMPLOYEE;
-- select ENAME, SAL*12 as ANNUAL_SALARY from EMPLOYEE;
-- select * from EMPLOYEE where DEPTNO =10;
-- select ENAME,JOB from EMPLOYEE where JOB="CLERK";
 -- select ENAME from EMPLOYEE where ENAME LIKE "S%";
 -- select ENAME from EMPLOYEE where ENAME LIKE "_L%";
 -- select ENAME from EMPLOYEE where ENAME like "%AR%";
-- select * from EMPLOYEE where year(HIREDATE)=1981;
-- select ENAME,SAL from EMPLOYEE where SAL>2500;
-- select * from EMPLOYEE where JOB != 'MANAGER';
-- select * from EMPLOYEE where COMM is  not null;
-- select * from EMPLOYEE where MGR is null;
-- select * from EMPLOYEE where DEPTNO=30 and JOB = "Salesman";
-- SELECT ENAME FROM EMPLOYEE WHERE JOB IN ('CLERK', 'ANALYST');
-- SELECT ENAME FROM EMPLOYEE WHERE SAL BETWEEN 1000 AND 2000;
-- SELECT * FROM EMPLOYEE ORDER BY ENAME;
 -- SELECT * FROM EMPLOYEE ORDER BY DEPTNO, SAL DESC;
 -- select count(*) from EMPLOYEE;
--  SELECT SUM(SAL) FROM EMPLOYEE;
 -- SELECT AVG(SAL) FROM EMPLOYEE;
 -- SELECT MAX(SAL), MIN(SAL) FROM EMPLOYEE;
-- SELECT DEPTNO, COUNT(*) FROM EMPLOYEE GROUP BY DEPTNO;
-- SELECT JOB, AVG(SAL)FROM EMPLOYEE GROUP BY JOB;
 -- SELECT DEPTNO, SUM(SAL)FROM EMPLOYEE GROUP BY DEPTNO;
 -- SELECT DEPTNO FROM EMPLOYEE GROUP BY DEPTNO HAVING COUNT(*) > 3;
-- SELECT JOB FROM EMPLOYEE GROUP BY JOB HAVING AVG(SAL) > 2000;
-- SELECT E.ENAME, D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO;
-- SELECT E.ENAME, D.DNAME, D.LOC FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO; 
-- SELECT E.ENAME AS EMPLOYEE, M.ENAME AS MANAGER FROM EMPLOYEE E LEFT JOIN EMPLOYEE M ON E.MGR = M.EMPNO;
-- SELECT E.ENAME, E.SAL, G.GRADE FROM EMPLOYEE E JOIN GRADE G ON E.SAL BETWEEN G.LOSAL AND G.HISAL;
-- SELECT E.ENAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO WHERE D.LOC = 'NEW YORK';
-- SELECT D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPTNO = D.DEPTNO WHERE E. ENAME = 'SMITH';
-- SELECT ENAME FROM EMPLOYEE WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'ALLEN');
-- SELECT ENAME FROM EMPLOYEE WHERE DEPTNO = (SELECT DEPTNO FROM EMPLOYEE WHERE ENAME = 'SCOTT');
-- SELECT ENAME FROM EMPLOYEE WHERE JOB = (SELECT JOB FROM EMPLOYEE WHERE ENAME = 'JONES');
-- SELECT MGR FROM EMPLOYEE GROUP BY MGR HAVING COUNT(*) > 2;
-- SELECT LOWER(ENAME) FROM EMPLOYEE;
-- SELECT SUBSTRING(ENAME,1,3) FROM EMPLOYEE;
-- SELECT ENAME, LENGTH(ENAME) FROM EMPLOYEE;
-- SELECT ENAME, ROUND(SAL, -3) FROM EMPLOYEE;
-- SELECT ENAME, MOD(SAL,1000) FROM EMPLOYEE;
-- SELECT NOW();
-- SELECT ENAME, YEAR(HIREDATE) FROM EMPLOYEE;
-- SELECT ENAME, MONTHNAME(HIREDATE) FROM EMPLOYEE;
-- SELECT ENAME, (2025 - YEAR(HIREDATE)) AS YEARS_WORKED FROM EMPLOYEE;
-- CREATE TABLE DEPARTMENT (DEPTNO INT PRIMARY KEY,DNAME VARCHAR(50),LOC VARCHAR(50));
-- ALTER TABLE DEPARTMENT ADD PINCODE INT;
-- SELECT * FROM DEPARTMENT;
-- INSERT INTO DEPARTMENT (DEPTNO, DNAME, LOC) VALUES (50, 'HR', 'HOUSTON');
-- UPDATE DEPARTMENT SET LOC = 'ATLANTA' WHERE DNAME = 'SALES';
-- DELETE FROM DEPARTMENT WHERE DNAME = 'OPERATIONS';









 







